name: Playwright Tests (PyCharm)

on:
  schedule:
    - cron: '30 18 * * *'  # Runs at 6:30 PM UTC
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Use a valid version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-html pytest-check

      - name: Install Playwright
        run: |
            pip install playwright
            playwright install

      - name: Run Tests with Video & Screenshot Comparison
        run: pytest --capture=no

      - name: Upload Videos & Screenshots as Artifacts
        uses: actions/upload-artifact@v4  # ✅ Updated version
        with:
          name: test-results
          path: |
            videos/
            screenshots/

      - name: Run Playwright tests
        run: pytest tests/

      - name: Install Playwright Browsers
        run: playwright install --with-deps